ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE goal_cycles DISABLE ROW LEVEL SECURITY;
ALTER TABLE goals DISABLE ROW LEVEL SECURITY;
ALTER TABLE achievements DISABLE ROW LEVEL SECURITY;
ALTER TABLE shared_goal_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE checkin_comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;
